language: node_js
sudo: required
dist: xenial
addons:
    chrome: stable
node_js:
- 10
env:
  global:
  - CHROMEDRIVER_VERSION=LATEST
  - NODE_ENV=production
  - NODE_OPTIONS=--max-old-space-size=7250
  - NPM_TAG=latest
  - RELEASE_VERSION="0.1.0-prerelease.$(date +'%Y%m%d%H%M%S')"
cache:
  directories:
  - node_modules
before_install:
- cd ..
- git clone https://${GH_TOKEN}@github.com/fmilano/scratch-vm.git scratch-vm
- cd scratch-vm
- npm install
- npm link
- cd ../scratch-gui
install:
- npm install
- npm link scratch-vm
script:
- npm run-script build
#- npm test
before_deploy:
- >
  if [ -z "$BEFORE_DEPLOY_RAN" ]; then
    npm --no-git-tag-version version $RELEASE_VERSION
    if [ "$TRAVIS_BRANCH" == "master" ]; then export NPM_TAG=stable; fi
    if [[ "$TRAVIS_BRANCH" == hotfix/* ]]; then export NPM_TAG=hotfix; fi # double brackets are important for matching the wildcard
    git config --global user.email $(git log --pretty=format:"%ae" -n1)
    git config --global user.name $(git log --pretty=format:"%an" -n1)
    export BEFORE_DEPLOY_RAN=true
  fi
deploy:
- provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: build
  on:
    branch: develop